from enum import IntEnum


class Function(IntEnum):
    SEARCH_CONTROLLER = 0x94
    SET_CONTROLLER_IP = 0x96
    QUERY_CONTROLLER_STATUS = 0x20
    READ_DATETIME = 0x32
    SET_DATETIME = 0x30
    GET_RECORD_BY_INDEX = 0xb0
    SET_READ_INDEX = 0xb2
    GET_READ_INDEX = 0xb4
    REMOTE_OPEN_DOOR = 0x40
    ADD_OR_UPDATE_PRIVILEGE = 0x50
